[workspace]
resolver = "2"
members = [
    "crates/*",
    "server",
    "workers/scanner",
    "workers/scheduler"
]

[workspace.package]
license = "MIT OR Apache-2.0"
edition = "2024"

[workspace.dependencies]
mockall = "0.15.0"
thiserror = "2.0.21"
reconductor-messaging = { path = "crates/messaging" }
