services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: reconductor
      POSTGRES_DB: reconductor
      POSTGRES_PASSWORD: reconductor
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DASHBOARD_URL: http://localhost:3000
      DATABASE_URL: postgres://reconductor:reconductor@db:5432/reconductor
      NODE_ENV: production
    ports:
      - 4000:4000

  dashboard:
    build: ./dashboard
    depends_on:
      - backend
    ports:
      - 3000:80


