services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: reconductor
      POSTGRES_DB: reconductor
      POSTGRES_PASSWORD: reconductor
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reconductor -d reconductor"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DASHBOARD_URL: http://localhost:3000
      DATABASE_URL: postgres://reconductor:reconductor@db:5432/reconductor
      NODE_ENV: production
    ports:
      - 4000:4000
    command: sh -c "./migration && ./server"

  dashboard:
    build: ./dashboard
    depends_on:
      - backend
    ports:
      - 3000:80


