import { z } from 'zod';
import { MAX_PASSWORD_LENGTH, MAX_USERNAME_LENGTH, MIN_PASSWORD_LENGTH, MIN_USERNAME_LENGTH, Z_PASSWORD_LENGTH_ERROR_MESSAGE, Z_PASSWORD_STRING_ERROR_MESSAGE, Z_USERNAME_LENGTH_ERROR_MESSAGE, Z_USERNAME_STRING_ERROR_MESSAGE } from '../constants';


export const registerSchema = z.object({
    username: z
        .string(Z_USERNAME_STRING_ERROR_MESSAGE)
        .min(MIN_USERNAME_LENGTH, { error: Z_USERNAME_LENGTH_ERROR_MESSAGE })
        .max(MAX_USERNAME_LENGTH, { error: Z_USERNAME_LENGTH_ERROR_MESSAGE }),
    password: z
        .string(Z_PASSWORD_STRING_ERROR_MESSAGE)
        .min(MIN_PASSWORD_LENGTH, { error: Z_PASSWORD_LENGTH_ERROR_MESSAGE })
        .max(MAX_PASSWORD_LENGTH, { error: Z_PASSWORD_LENGTH_ERROR_MESSAGE })
});

