[package]
name = "scanner"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
dotenvy = "0.15.7"
futures-lite = "2.6.1"
lapin = "4.4.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sqlx = { version = "0.8.6", features = ["ipnetwork"] }
tokio = { version = "1.51.0", features = ["full"] }
tracing = "0.1.44"
uuid = { version = "1.23.0", features = ["serde"] }
