type Project {
  id: ID!
  name: String!
  created_at: String!
}

type Scan {
  id: ID!
  target: String!
  created_at: String!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type ProjectEdge {
  cursor: String!
  node: Project!
}

type ProjectConnection {
  edges: [ProjectEdge!]!
  pageInfo: PageInfo!
}

type Query {
  projects(first: Int, after: String): ProjectConnection!
  project(id: ID!): Project
}

input CreateProjectInput {
  name: String!
}

type Mutation {
  createProject(input: CreateProjectInput!): Project!
}
