type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type ValidationError {
  field: String!
  message: String!
}

type Project {
  id: ID!
  name: String!
  created_at: String!
}

type ProjectEdge {
  cursor: String!
  node: Project!
}

type CreateProjectPayload {
  edge: ProjectEdge
  errors: [ValidationError!]!
}

type ProjectConnection {
  edges: [ProjectEdge!]!
  pageInfo: PageInfo!
}

type Scan {
  id: ID!
  target: String!
  status: String!
  created_at: String!
  schedule: String
}

type ScanEdge {
  cursor: String!
  node: Scan!
}

type CreateScanPayload {
  edge: ScanEdge
  errors: [ValidationError!]!
}

type ScanConnection {
  edges: [ScanEdge!]!
  pageInfo: PageInfo!
}

type Host {
  id: ID!
  created_at: String!
  ip: String
  mac: String
  hostname: String
  vendor: String
  os_match: String
  os_accuracy: Int
}

type HostEdge {
  cursor: String!
  node: Host!
}

type HostConnection {
  edges: [HostEdge!]!
  pageInfo: PageInfo!
}

type Port {
  id: ID!
  created_at: String!
  port: Int!
  protocol: String
  state: String
  service: String
  product: String
  version: String
}

type PortEdge {
  cursor: String!
  node: Port!
}

type PortConnection {
  edges: [PortEdge!]!
  pageInfo: PageInfo!
}

type Query {
  projects(first: Int, after: String): ProjectConnection!
  project(id: ID!): Project
  scans(first: Int, after: String): ScanConnection!
}

input CreateProjectInput {
  name: String!
}

input CreateScanInput {
  target: String!
  projectId: String!
  schedule: String
}

type Mutation {
  createProject(input: CreateProjectInput!): CreateProjectPayload!
  createScan(input: CreateScanInput!): CreateScanPayload!
}
