name: Test Scheduler
permissions:
  contents: read
on:
  push:
  pull_request:

jobs:
  deny:
    uses: ./.github/workflows/deny.yml
  tests:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v6
      - name: Install sqlx-cli
        run: cargo install sqlx-cli
      - name: Run platform tests
        run: ./platform_tests.sh
        working-directory: ./workers/scheduler
        env:
          DATABASE_URL: postgres://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${{ vars.DB_HOST }}:${{ vars.DB_PORT }}/${{ vars.DB_NAME }}
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_NAME: ${{ vars.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

