name: Test Backend
on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v6
      - name: Install sqlx-cli
        run: cargo install sqlx-cli
      - name: Run tests
        run: ./tests.sh
        working-directory: ./server
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          DASHBOARD_URL: ${{ secrets.DASHBOARD_URL }}
          CSRF_SECRET: ${{ secrets.CSRF_SECRET }}

