name: Test Scheduler
on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v6
      - name: Install sqlx-cli
        run: cargo install sqlx-cli
      - name: Run platform tests
        run: ./platform_tests.sh
        working-directory: ./workers/scheduler
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_URL: ${{ secrets.REDIS_URL }}

